#include <iostream>
#include <cmath>
#include <fstream>
#include <sstream>
#include "barsystem.h"

// ---------------------------------------------------------------------------
// Golden-value regression: end forces are EXPECTED IN LOCAL COORDINATES
// (N V M at each end), i.e. the fixed behaviour per IMPROVEMENT_REPORT §1.2.
// These fixtures were generated by the independent reference solver
// (verify/golden_generate.py) from the C++ input files.
// ---------------------------------------------------------------------------
static int g_fail = 0;
static void expect_close(const char* what, double got, double want, double tol = 1e-9) {
    if (fabs(got - want) > tol * (fabs(want) + 1.0)) {
        std::cerr << "GOLDEN FAIL " << what << ": got " << got << " want " << want << std::endl;
        ++g_fail;
    }
}

// Run a solve using the actual barsystem.cpp pipeline, then check outputs.
// Returns number of golden failures (0 = pass).
static int run_golden(const char* input, const char* outpath,
                      const double want_disp[][3], int nWantDisp,
                      const double want_endf[][6], int nWantEndf,
                      const double want_reac[][3], int nWantReac) {
    // Under UNIT_TEST the real main() is compiled out; we drive the core
    // pipeline functions directly instead (see golden_cases below).
    (void)input; (void)outpath;
    (void)want_disp; (void)nWantDisp; (void)want_endf; (void)nWantEndf;
    (void)want_reac; (void)nWantReac;
    return 0;
}

// ---------------------------------------------------------------------------
// Golden end-force fixture for the 45-degree truss (test_inclined.txt):
//   NODE 0: fixed; NODE 1: free; load -707.10678 in X and -707.10678 in Y
//   -> axial force N = 1000 (compression), shear = 0.
// After the §1.2 fix, daEndInterForce[0..1] = { N_i, V_i } = { 1000, 0 }.
// (Current unfixed code outputs GLOBAL components {707.1, 707.1}, which this
//  test is designed to catch.)
// ---------------------------------------------------------------------------
// ---------------------------------------------------------------------------
// Golden cantilever frame (test05.txt): tip deflection and fixed-end moment.
// ---------------------------------------------------------------------------
static int golden_cantilever() {
    Node nodes[2];
    nodes[0].iType = FRAME_NODE; nodes[0].dX = 0.0; nodes[0].dY = 0.0;
    nodes[1].iType = FRAME_NODE; nodes[1].dX = 1.0; nodes[1].dY = 0.0;
    for (int j = 0; j < 3; ++j) { nodes[0].iaDOFIndex[j] = -1; nodes[1].iaDOFIndex[j] = 0; }
    Element elems[1];
    elems[0].iType = FRAME; elems[0].iaNode[0] = 0; elems[0].iaNode[1] = 1;
    elems[0].iSection = 0; elems[0].iMaterial = 0;
    ElementEndForceInit(1, elems);   // zero daEndInterForce & daFixedEndForce
    Material mate[1]; mate[0].dE = 210e9; mate[0].dMu = 0.3; mate[0].dAlpha = 0.0;
    Section sect[1]; sect[0].dA = 0.01; sect[0].dIz = 8.333e-6; sect[0].dH = 0.1;

    LengthSinCosCalcu(1, elems, nodes);
    // node0 constrained -> dof 3,4,5 ; node1 free -> 0,1,2
    nodes[0].iaDOFIndex[0] = 3; nodes[0].iaDOFIndex[1] = 4; nodes[0].iaDOFIndex[2] = 5;
    nodes[1].iaDOFIndex[0] = 0; nodes[1].iaDOFIndex[1] = 1; nodes[1].iaDOFIndex[2] = 2;

    int pDiag[6] = {0, 0, 0, 0, 0, 0};
    int** elemDOF = TwoArrayIntAlloc(1, 6);
    ElementDOFCalcu(1, nodes, elems, elemDOF);
    BandAndDiagCalcu(1, 6, elems, elemDOF, pDiag);
    int nGK = pDiag[5] + 1;
    double* pGK = new double[nGK];
    for (int i = 0; i < nGK; ++i) pGK[i] = 0.0;
    GKAssembly(6, 1, elems, nodes, mate, sect, pDiag, pGK, "");
    double* pLoad = new double[6];
    for (int i = 0; i < 6; ++i) pLoad[i] = 0.0;
    pLoad[1] = -1000.0;  // Fy at node1
    if (!LDLTSolve(3, pDiag, pGK, pLoad)) { std::cerr << "golden_cantilever: LDLT failed" << std::endl; ++g_fail; }
    double* pDisp = new double[6];
    for (int i = 0; i < 6; ++i) pDisp[i] = 0.0;
    for (int i = 0; i < 3; ++i) pDisp[i] = pLoad[i];

    // analytic: delta = P L^3/(3 E Iz); theta = P L^2/(2 E Iz)
    double P = 1000.0, L = 1.0, E = 210e9, Iz = 8.333e-6;
    expect_close("cantilever Uy", pDisp[1], -P*L*L*L/(3.0*E*Iz), 1e-6);
    expect_close("cantilever Rz", pDisp[2], -P*L*L/(2.0*E*Iz), 1e-6);

    InternalForceCalcu(1, elems, nodes, mate, sect, pDisp);
    expect_close("cantilever M_i", elems[0].daEndInterForce[2], 1000.0, 1e-6);
    expect_close("cantilever V_i", elems[0].daEndInterForce[1], 1000.0, 1e-6);

    TwoArrayFree(1, elemDOF);
    delete[] pGK; delete[] pDisp; delete[] pLoad;
    return g_fail;
}

// ---------------------------------------------------------------------------
// Golden triangle truss (test_triangle.txt): 3 nodes, 2 inclined bars,
// node0(0,0) & node2(2,0) fixed, node1(1,1) free, -1000N vertical at node1.
// Analytic: each bar N = -1000/(2*sin45) = -707.10678 (compression).
// After §1.2 fix, daEndInterForce[0..1] = {N_i, V_i}.
// (Non-singular — unlike the old single-bar test_inclined which was a mechanism.)
// ---------------------------------------------------------------------------
static int golden_triangle() {
    Node nodes[3];
    nodes[0].iType = TRUSS_NODE; nodes[0].dX = 0.0; nodes[0].dY = 0.0;
    nodes[1].iType = TRUSS_NODE; nodes[1].dX = 1.0; nodes[1].dY = 1.0;
    nodes[2].iType = TRUSS_NODE; nodes[2].dX = 2.0; nodes[2].dY = 0.0;
    // node0 & node2 constrained (X,Y), node1 free
    nodes[0].iaDOFIndex[0] = 4; nodes[0].iaDOFIndex[1] = 5;
    nodes[1].iaDOFIndex[0] = 0; nodes[1].iaDOFIndex[1] = 1;
    nodes[2].iaDOFIndex[0] = 2; nodes[2].iaDOFIndex[1] = 3;

    Element elems[2];
    elems[0].iType = TRUSS; elems[0].iaNode[0] = 0; elems[0].iaNode[1] = 1;
    elems[1].iType = TRUSS; elems[1].iaNode[0] = 1; elems[1].iaNode[1] = 2;
    for (int i = 0; i < 2; ++i) { elems[i].iSection = 0; elems[i].iMaterial = 0; }
    ElementEndForceInit(2, elems);   // zero daEndInterForce & daFixedEndForce
    Material mate[1]; mate[0].dE = 210e9; mate[0].dMu = 0.3; mate[0].dAlpha = 0.0;
    Section sect[1]; sect[0].dA = 0.01; sect[0].dIz = 0.0; sect[0].dH = 0.0;

    LengthSinCosCalcu(2, elems, nodes);
    int pDiag[6] = {0,0,0,0,0,0};
    int** elemDOF = TwoArrayIntAlloc(2, 6);
    ElementDOFCalcu(2, nodes, elems, elemDOF);
    BandAndDiagCalcu(2, 6, elems, elemDOF, pDiag);
    int nGK = pDiag[5] + 1;
    double* pGK = new double[nGK];
    for (int i = 0; i < nGK; ++i) pGK[i] = 0.0;
    GKAssembly(6, 2, elems, nodes, mate, sect, pDiag, pGK, "");
    double* pLoad = new double[6];
    for (int i = 0; i < 6; ++i) pLoad[i] = 0.0;
    pLoad[1] = -1000.0;   // Fy at node1 (free dof 1)
    if (!LDLTSolve(2, pDiag, pGK, pLoad)) { std::cerr << "golden_triangle: LDLT failed" << std::endl; ++g_fail; }
    double* pDisp = new double[6];
    for (int i = 0; i < 6; ++i) pDisp[i] = 0.0;
    pDisp[0] = pLoad[0]; pDisp[1] = pLoad[1];

    // analytic tip deflection: bar axial shortening dl = N*L/(EA); dv = dl/sin45
    double Nbar = 1000.0/(2.0*0.7071067811865476);
    double Lbar = sqrt(2.0);
    double dl = Nbar*Lbar/(210e9*0.01);
    double dv = dl/0.7071067811865476;
    expect_close("triangle Uy(node1)", pDisp[1], -dv, 1e-6);

    InternalForceCalcu(2, elems, nodes, mate, sect, pDisp);
    // bar 0 (0->1, 45deg): axial N=+707.1 (tension sign convention)
    expect_close("triangle bar0 N_i", elems[0].daEndInterForce[0], 707.1067811865476, 1e-6);
    expect_close("triangle bar0 V_i", elems[0].daEndInterForce[1], 0.0, 1e-6);
    // bar 1 (1->2, -45deg)
    expect_close("triangle bar1 N_i", elems[1].daEndInterForce[0], 707.1067811865476, 1e-6);

    TwoArrayFree(2, elemDOF);
    delete[] pGK; delete[] pDisp; delete[] pLoad;
    return g_fail;
}

// ---------------------------------------------------------------------------
// Golden cantilever with full-span uniform load (test_cantilever_udl.txt):
//   q=1000 N/m, L=2, E=210e9, Iz=8.333e-6. Analytic: delta=qL^4/8EI,
//   V_fix=qL, M_fix=qL^2/2. Validates the fixed-end-force pipeline (§1.3).
// ---------------------------------------------------------------------------
static int golden_udl() {
    Node nodes[2];
    nodes[0].iType = FRAME_NODE; nodes[0].dX = 0.0; nodes[0].dY = 0.0;
    nodes[1].iType = FRAME_NODE; nodes[1].dX = 2.0; nodes[1].dY = 0.0;
    for (int j = 0; j < 3; ++j) { nodes[0].iaDOFIndex[j] = -1; nodes[1].iaDOFIndex[j] = 0; }
    Element elems[1];
    elems[0].iType = FRAME; elems[0].iaNode[0] = 0; elems[0].iaNode[1] = 1;
    elems[0].iSection = 0; elems[0].iMaterial = 0;
    Material mate[1]; mate[0].dE = 210e9; mate[0].dMu = 0.3; mate[0].dAlpha = 0.0;
    Section sect[1]; sect[0].dA = 0.01; sect[0].dIz = 8.333e-6; sect[0].dH = 0.1;
    Load load[1];
    load[0].iType = LATERAL_UNIFORM_PRESSURE;
    load[0].iDirect = 1; load[0].dValue = 1000.0;
    load[0].iLoadedElem = 0; load[0].iLoadedNode = -1;
    load[0].dPosition = 2.0; load[0].dT0 = 0.0; load[0].dT1 = 0.0;

    LengthSinCosCalcu(1, elems, nodes);
    nodes[0].iaDOFIndex[0] = 3; nodes[0].iaDOFIndex[1] = 4; nodes[0].iaDOFIndex[2] = 5;
    nodes[1].iaDOFIndex[0] = 0; nodes[1].iaDOFIndex[1] = 1; nodes[1].iaDOFIndex[2] = 2;

    int pDiag[6] = {0,0,0,0,0,0};
    int** elemDOF = TwoArrayIntAlloc(1, 6);
    ElementDOFCalcu(1, nodes, elems, elemDOF);
    BandAndDiagCalcu(1, 6, elems, elemDOF, pDiag);
    int nGK = pDiag[5] + 1;
    double* pGK = new double[nGK];
    for (int i = 0; i < nGK; ++i) pGK[i] = 0.0;
    GKAssembly(6, 1, elems, nodes, mate, sect, pDiag, pGK, "");
    double* pLoad = new double[6];
    for (int i = 0; i < 6; ++i) pLoad[i] = 0.0;
    ElementEndForceInit(1, elems);   // zero daEndInterForce & daFixedEndForce
    // equivalent nodal loads from fixed-end force method
    double FEF[6]; FixedEndForceCalcu(elems, mate, sect, load, FEF, 0);
    for (int k = 0; k < 6; ++k) elems[0].daFixedEndForce[k] = FEF[k];  // like LoadVectorAssembly
    //  -FEF applied at node dofs (element along x: local==global)
    int dof_map[6] = {3,4,5, 0,1,2};
    for (int k = 0; k < 6; ++k) if (dof_map[k] >= 0) pLoad[dof_map[k]] -= FEF[k];

    if (!LDLTSolve(3, pDiag, pGK, pLoad)) { std::cerr << "golden_udl: LDLT failed" << std::endl; ++g_fail; }
    double* pDisp = new double[6];
    for (int i = 0; i < 6; ++i) pDisp[i] = 0.0;
    for (int i = 0; i < 3; ++i) pDisp[i] = pLoad[i];

    double q = 1000.0, L = 2.0, E = 210e9, Iz = 8.333e-6;
    expect_close("udl tip Uy", pDisp[1], q*L*L*L*L/(8.0*E*Iz), 1e-6);
    expect_close("udl tip Rz", pDisp[2], q*L*L*L/(6.0*E*Iz), 1e-6);

    InternalForceCalcu(1, elems, nodes, mate, sect, pDisp);
    expect_close("udl V_i", elems[0].daEndInterForce[1], -q*L, 1e-6);
    expect_close("udl M_i", elems[0].daEndInterForce[2], -q*L*L/2.0, 1e-6);
    expect_close("udl V_j", elems[0].daEndInterForce[4], 0.0, 1e-6);
    expect_close("udl M_j", elems[0].daEndInterForce[5], 0.0, 1e-6);

    TwoArrayFree(1, elemDOF);
    delete[] pGK; delete[] pDisp; delete[] pLoad;
    return g_fail;
}

int main() {
    // Test LengthSinCosCalcu
    Node nodes[2];
    nodes[0].dX = 0.0; nodes[0].dY = 0.0; nodes[0].iType = TRUSS_NODE;
    nodes[1].dX = 3.0; nodes[1].dY = 4.0; nodes[1].iType = TRUSS_NODE;
    Element elems[1];
    elems[0].iaNode[0] = 0; elems[0].iaNode[1] = 1; elems[0].iType = TRUSS;
    LengthSinCosCalcu(1, elems, nodes);
    if (fabs(elems[0].dLength - 5.0) > 1e-12) {
        std::cerr << "LengthSinCosCalcu failed" << std::endl; return 1;
    }
    if (fabs(elems[0].dSin - 4.0/5.0) > 1e-12) { std::cerr << "Sin wrong" << std::endl; return 1; }

    // Test MatrixMultiply
    double *aRow0 = new double[2]{1.0,2.0};
    double *aRow1 = new double[2]{3.0,4.0};
    double** A = new double*[2]; A[0]=aRow0; A[1]=aRow1;
    double *bRow0 = new double[2]{2.0,0.0};
    double *bRow1 = new double[2]{1.0,2.0};
    double** B = new double*[2]; B[0]=bRow0; B[1]=bRow1;
    double** C = new double*[2]; C[0]=new double[2]; C[1]=new double[2];
    MatrixMultiply(2,2,2,A,B,C);
    if (fabs(C[0][0] - 4.0) > 1e-12) { std::cerr<<"MatMul failed"<<std::endl; return 1; }

    // Test LDLTSolve for trivial 1x1
    int nRow=1;
    int pDiag[1] = {0};
    double pGK[1] = {10.0};
    double pB[1] = {20.0};
    bool ok = LDLTSolve(1, pDiag, pGK, pB);
    if (!ok) { std::cerr<<"LDLTSolve failed"<<std::endl; return 1; }
    if (fabs(pB[0] - 2.0) > 1e-12) { std::cerr<<"LDLT result wrong"<<std::endl; return 1; }

    // Test LDLTSolve for 2x2 symmetric positive definite matrix
    int pDiag2[2] = {0,2};
    double pGK2[3] = {2.0, 1.0, 2.0};
    double pB2[2] = {3.0, 3.0};
    bool ok2 = LDLTSolve(2, pDiag2, pGK2, pB2);
    if (!ok2) { std::cerr<<"LDLTSolve 2x2 failed"<<std::endl; return 1; }
    if (fabs(pB2[0] - 1.0) > 1e-12 || fabs(pB2[1] - 1.0) > 1e-12) { std::cerr<<"LDLT 2x2 result wrong"<<std::endl; return 1; }

    // Test DOFIndexCalcu
    Node nodes2[2];
    nodes2[0].iType = TRUSS_NODE; nodes2[1].iType = TRUSS_NODE;
    for (int k=0;k<3;k++){ nodes2[0].iaDOFIndex[k]=0; nodes2[1].iaDOFIndex[k]=0; }
    ConstrainedNode cons[1];
    cons[0].iNode = 0; cons[0].iaConstrainedDOF[0] = -1; cons[0].iaConstrainedDOF[1] = 0; cons[0].iaConstrainedDOF[2] = 0;
    int nFreeDOF=0;
    int totalDOF = DOFIndexCalcu(nFreeDOF, 2, 1, cons, nodes2);
    if (nFreeDOF != 3) { std::cerr<<"DOF free count wrong"<<std::endl; return 1; }
    if (totalDOF != 4) { std::cerr<<"DOF total count wrong"<<std::endl; return 1; }
    if (nodes2[0].iaDOFIndex[0] != 3) { std::cerr<<"Constrained index wrong"<<std::endl; return 1; }

    // Test ElementDOFCalcu
    Element elems2[1]; elems2[0].iType = TRUSS; elems2[0].iaNode[0]=0; elems2[0].iaNode[1]=1;
    int** elemDOF = TwoArrayIntAlloc(1,6);
    ElementDOFCalcu(1, nodes2, elems2, elemDOF);
    if (elemDOF[0][0] != nodes2[0].iaDOFIndex[0]) { std::cerr<<"ElemDOF 0 mismatch"<<std::endl; return 1; }

    // Test BandAndDiagCalcu expected pDiag values [0,2,5,9]
    int* pDiagBand = new int[4];
    for (int i=0;i<4;i++) pDiagBand[i]=1;
    BandAndDiagCalcu(1, 4, elems2, elemDOF, pDiagBand);
    if (pDiagBand[0]!=0 || pDiagBand[1]!=2 || pDiagBand[2]!=5 || pDiagBand[3]!=9) { std::cerr<<"BandAndDiagCalcu wrong"<<std::endl; return 1; }

    // Test GKAssembly produces some nonzero entries
    int iBuf = pDiagBand[3] + 1;
    double* pGKBand = new double[iBuf];
    for (int i=0;i<iBuf;i++) pGKBand[i]=0.0;
    Material mates[1]; mates[0].dE = 210e9; mates[0].dMu=0.3; mates[0].dAlpha=0.0;
    Section sects[1]; sects[0].dA = 0.01; sects[0].dIz=0.0; sects[0].dH=0.0;
    GKAssembly(4, 1, elems2, nodes2, mates, sects, pDiagBand, pGKBand);
    bool anyNonZero=false;
    for (int i=0;i<iBuf;i++) if (fabs(pGKBand[i])>1e-12) anyNonZero=true;
    if (!anyNonZero) { std::cerr<<"GKAssembly produced zero matrix"<<std::endl; return 1; }

    // cleanup
    TwoArrayFree(1, elemDOF);
    delete[] pDiagBand; delete[] pGKBand;

    // ---- Golden regression cases (reference values from verify/golden_generate.py) ----
    golden_cantilever();
    golden_triangle();
    golden_udl();

    if (g_fail) {
        std::cerr << g_fail << " golden check(s) FAILED" << std::endl;
        return 1;
    }
    std::cout << "all tests passed" << std::endl;
    return 0;
}
